baseurl = "https://tars.pages.dev/"
title = "Cell Sanctuary"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "kksudo"
enableGitInfo = true

[params]
author = "Cell Sanctuary"
info = ["Got a Glitch? Get a Fix!"]
description = "Cell Sanctuary's social page"
keywords = "blog,businesscard,personal,devops"
avatarurl = "https://imgur.com/a/VuRTHmB.png"

since = 2023
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/kksudo/kazakov.xyz/tree/"
powered_by = true
# Series see also post count
maxSeeAlsoItems = 6

[taxonomies]
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Facebook"
icon = "fa fa-facebook fa-2x"
weight = 1
url = "https://www.facebook.com/CellSanctuaryZA/"
target = "_blank"
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 2
url = "https://twitter.com/CellSanctuaryZA/"
target = "_blank"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://instagram.com/CellSanctuaryZA/"
target = "_blank"
[[params.social]]
name = "YouTube"
icon = "fa fa-youtube fa-2x"
weight = 4
url = "https://www.youtube.com/@CellSanctuaryZA/"
target = "_blank"
[[params.social]]
name = "Tiktok"
icon = "fa fa-tiktok fa-2x"
weight = 5
url = "https://www.tiktok.com/@CellSanctuaryZA/"
target = "_blank"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "Reviews"
weight = 2
url = "about/"


