baseurl = "https://kazakov.xyz"
title = "DevOps with love"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "kksudo"

[params]
author = "Kirill Kazakov"
info = "Full Stack DevOps and Magician"
description = "Kirill Kazakov's personal website"
keywords = "blog,developer,personal,devops"
#avatarurl = "images/avatar.jpg"
gravatar = "k@kazakov.xyz"

#favicon_32 = "/img/favicon-32x32.png"
#favicon_16 = "/img/favicon-16x16.png"

since = 2010

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

#customCSS = ["css/custom.css"]
#customSCSS = ["scss/custom.scss"]
#customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/kksudo/"
target = "_blank"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/kk_sudo/"
target = "_blank"
[[params.social]]
name = "Linkedin"
icon = "fa fa-linkedin fa-2x"
weight = 5
url = "https://www.linkedin.com/in/kazakovk/"
target = "_blank"
[[params.social]]
name = "k@kazakov.xyz"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:k@kazakov.xyz"
target = "_blank"

[languages.en]
languageName = ":ru:"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"


