baseurl = "https://kazakov.xyz"
title = "TARS Tech SA"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "kksudo"
enableGitInfo = true

[params]
author = "TARS Tech SA"
info = ["Got a Glitch? Get a Fix!"]
description = "TARS Tech SA's social page"
keywords = "blog,businesscard,personal,devops"
avatarurl = "https://i.imgur.com/UkaKzu8.jpeg"

since = 2023
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/kksudo/kazakov.xyz/tree/"
powered_by = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Facebook"
icon = "fa fa-facebook fa-2x"
weight = 1
url = "https://www.facebook.com/TARSTechSA/"
target = "_blank"
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 2
url = "https://twitter.com/TARSTechSA/"
target = "_blank"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://instagram.com/TARSTechSA/"
target = "_blank"
[[params.social]]
name = "Tiktok"
icon = "fa fa-tiktok fa-2x"
weight = 4
url = "https://www.tiktok.com/@TARSTechSA/"
target = "_blank"
[[params.social]]
name = "YouTube"
icon = "fa fa-tiktok fa-2x"
weight = 5
url = "https://www.youtube.com/@TARSTechSA/"
target = "_blank"
[[params.social]]
name = "TARS Tech SA"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:tarstechsa@gmail.com"
target = "_blank"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"


